export default {
  _id: "5f85950d670f81001c4214be",
  amount_paid: 0,
  print_ready: false,
  name: "Obinna Ekpendu",
  email: "",
  phone: "09066055171",
  gender: "Male",
  address: "Amapu Umuodo Ugwunagbor LGA",
  breach_type: "Right to fair hearing",
  inPrison: true,
  daysPlus: false,
  monthsPlus: true,
  arrested_on: "2019-05-08",
  arrested_at: "In his house",
  arraigned_at: "",
  arraigned_on: "2019-05-13",
  offence_charged: "Stealing",
  offence_suspected: "Stealing",
  case_mates: 0,
  itinerary: "",
  station: "Ihie Police station Ugwunagbor LGA",
  station2: "",
  station_duration: 0,
  station2_duration: 0,
  state_origin: "Abia State",
  state_residence: "Abia State",
  state_arrest: "Abia State",
  state_arraigned: "Abia State",
  adjournment_date: "2019-01-24T00:00:00Z",
  lga: "Ugwunagbo",
  beaten: "Yes matchet was used on him",
  injured: "Yes matchet cuts /wounds",
  bail_amount: 0,
  dpp: "Yes",
  caseType: "D",
  division: "Ukwa",
  first_accused: "",
  rep: "5f857162670f81001c4214b7",
  app_id: "d-0006",
  __v: 0,
};
