FROM node:14-alpine
LABEL maintainer="Peter Akaliro"

# Install Java

RUN apk add --no-cache openjdk8

# Create app directory
WORKDIR /app

RUN yarn global add nodemon

COPY package*.json ./

RUN yarn
# Bundle app source
COPY . .

EXPOSE 8080
CMD [ "yarn", "start-docker-dev" ]
